### PR TITLE
Write announcement for January 2015 meeting.

### PR DESCRIPTION
**Pull request by campbeja**

### CODE REVIEW

**Comment by DevinClark** [comment]
Looks good to me. :+1:

**Comment by the-simian** [comment]
im about to look over this

**Comment by the-simian** [comment]
ah yeah really nice, and the poster is nice too

**Comment by campbeja** [comment]
The changes haves not deployed to gh-pages branch. Take one more look and if you love it, say "FANTABULOUS!" and run `hexo deploy --generate`

**Comment by amandaharlin** [comment]
lol :sparkles:

**Comment by campbeja** [comment]
Changes never got published, I just took care of it. GitHub would not let me reopen issues, so I settled for commenting. I'll just post a new issue next time.

**Pull request merged**
