### PR TITLE
Continuous deployment of static site tool

### PR DESCRIPTION
**Pull request by davidroberts63**
For the January 2016 or February 2016 meeting. Not sure which one Amanda wanted so I just went with January for now. **Things I still need to do**:

* Create an image
* Update meetup url

* Oh and finish prepping the talk ;-). Like I said, I've done a talk in two week in the past, this one will be easy.

### CODE REVIEW

**Comment by seejessicacode** [comment]
@davidroberts63 - @amandaharlin said you're set for January 2016. We really appreciate it!

I updated Meetup. For your bio, I hi-jacked the first paragraph from your 'About' page and changed the pronouns. Please let me know if you would like me to change it.

**Comment by davidroberts63** [comment]
Looks good. I'll get an image for the website over the weekend. Gonna try to get a pic of my son with a van de Graff generator for the 'static'.

-----Original Message-----

**Comment by davidroberts63** [comment]
Done with my changes. Ready for push when you are.

**Comment by seejessicacode** [comment]
Thanks @davidroberts63! I have updated Meetup and scheduled the email for 9 am today.

I will test and publish tonight If @the-simian doesn't beat me to it.

**Comment by the-simian** [comment]
At this rate you might beat me

**Comment by seejessicacode** [comment]
Deployed! Thanks @davidroberts63

**Pull request merged**
