### PR TITLE
Write February Lightning Talk

### PR DESCRIPTION
**Pull request by campbeja**

### CODE REVIEW

**Comment by campbeja** [comment]
I was trying to assign both Amanda and Jesse to this pull request, looks like I can only choose one!

**Comment by DevinClark** [comment]
:+1:

**Comment by campbeja** [comment]
Just now saw that Meetup was updated with the approved lineup.

**Comment by campbeja** [comment]
Committed new changeset to include speaker lineup

**Comment by DevinClark** [comment]
Everything looks good to go to me. :+1: Great job Jessica!

**Comment by campbeja** [comment]
:shipit:

**Comment by the-simian** [comment]
oh cool, thansk for getting this

**Comment by the-simian** [comment]
This lineup looks really good too! some new speakers, and fun topics

**Comment by the-simian** [comment]
:shipit"

**Pull request merged**
